// Generated by scripts/generate-printer-presets.mjs - do not edit by hand.
// Source: OrcaSlicer resources/profiles (AGPL-3.0), commit 6be6fdd7c7dcb700f0310ea6337252d35cc43659.
// Build plate width x depth and maximum print height in millimetres, for the
// printer's standard 0.4 mm nozzle profile.

export type PrinterPreset = {
  id: string;
  vendor: string;
  model: string;
  width: number;
  depth: number;
  height: number;
};

export const PRINTER_PRESETS_SOURCE = "OrcaSlicer 6be6fdd";

export const PRINTER_PRESETS: readonly PrinterPreset[] = [
  {"id":"bambu-lab-a1-mini","vendor":"Bambu Lab","model":"A1 mini","width":180,"depth":180,"height":180},
  {"id":"bambu-lab-a1","vendor":"Bambu Lab","model":"A1","width":256,"depth":256,"height":256},
  {"id":"bambu-lab-p1p","vendor":"Bambu Lab","model":"P1P","width":256,"depth":256,"height":250},
  {"id":"bambu-lab-p1s","vendor":"Bambu Lab","model":"P1S","width":256,"depth":256,"height":250},
  {"id":"bambu-lab-p2s","vendor":"Bambu Lab","model":"P2S","width":256,"depth":256,"height":256},
  {"id":"bambu-lab-x1-carbon","vendor":"Bambu Lab","model":"X1 Carbon","width":256,"depth":256,"height":250},
  {"id":"bambu-lab-x1e","vendor":"Bambu Lab","model":"X1E","width":256,"depth":256,"height":250},
  {"id":"bambu-lab-h2s","vendor":"Bambu Lab","model":"H2S","width":340,"depth":320,"height":340},
  {"id":"bambu-lab-h2d","vendor":"Bambu Lab","model":"H2D","width":350,"depth":320,"height":325},
  {"id":"prusa-mini","vendor":"Prusa","model":"MINI","width":180,"depth":180,"height":180},
  {"id":"prusa-mk3s","vendor":"Prusa","model":"MK3S","width":250,"depth":210,"height":210},
  {"id":"prusa-mk3-5","vendor":"Prusa","model":"MK3.5","width":250,"depth":210,"height":210},
  {"id":"prusa-mk4","vendor":"Prusa","model":"MK4","width":250,"depth":210,"height":220},
  {"id":"prusa-mk4s","vendor":"Prusa","model":"MK4S","width":250,"depth":210,"height":220},
  {"id":"prusa-core-one","vendor":"Prusa","model":"CORE One","width":250,"depth":220,"height":270},
  {"id":"prusa-xl","vendor":"Prusa","model":"XL","width":360,"depth":360,"height":360},
  {"id":"creality-ender-3","vendor":"Creality","model":"Ender-3","width":220,"depth":220,"height":250},
  {"id":"creality-ender-3-v2","vendor":"Creality","model":"Ender-3 V2","width":220,"depth":220,"height":250},
  {"id":"creality-ender-3-s1","vendor":"Creality","model":"Ender-3 S1","width":220,"depth":220,"height":270},
  {"id":"creality-ender-3-v3-se","vendor":"Creality","model":"Ender-3 V3 SE","width":220,"depth":220,"height":250},
  {"id":"creality-ender-3-v3-ke","vendor":"Creality","model":"Ender-3 V3 KE","width":220,"depth":220,"height":245},
  {"id":"creality-ender-3-v3","vendor":"Creality","model":"Ender-3 V3","width":220,"depth":220,"height":250},
  {"id":"creality-ender-5-s1","vendor":"Creality","model":"Ender-5 S1","width":220,"depth":220,"height":300},
  {"id":"creality-cr-10","vendor":"Creality","model":"CR-10","width":300,"depth":300,"height":400},
  {"id":"creality-k1","vendor":"Creality","model":"K1","width":220,"depth":220,"height":250},
  {"id":"creality-k1c","vendor":"Creality","model":"K1C","width":220,"depth":220,"height":250},
  {"id":"creality-k1-max","vendor":"Creality","model":"K1 Max","width":300,"depth":300,"height":300},
  {"id":"creality-k2-plus","vendor":"Creality","model":"K2 Plus","width":350,"depth":350,"height":350},
  {"id":"elegoo-neptune-3-pro","vendor":"Elegoo","model":"Neptune 3 Pro","width":230,"depth":230,"height":280},
  {"id":"elegoo-neptune-4","vendor":"Elegoo","model":"Neptune 4","width":230,"depth":230,"height":265},
  {"id":"elegoo-neptune-4-pro","vendor":"Elegoo","model":"Neptune 4 Pro","width":230,"depth":230,"height":265},
  {"id":"elegoo-neptune-4-plus","vendor":"Elegoo","model":"Neptune 4 Plus","width":325,"depth":325,"height":385},
  {"id":"elegoo-neptune-4-max","vendor":"Elegoo","model":"Neptune 4 Max","width":426,"depth":426,"height":480},
  {"id":"elegoo-centauri-carbon","vendor":"Elegoo","model":"Centauri Carbon","width":256,"depth":256,"height":256},
  {"id":"anycubic-kobra-2-neo","vendor":"Anycubic","model":"Kobra 2 Neo","width":220,"depth":220,"height":250},
  {"id":"anycubic-kobra-3","vendor":"Anycubic","model":"Kobra 3","width":255,"depth":255,"height":260},
  {"id":"anycubic-kobra-s1","vendor":"Anycubic","model":"Kobra S1","width":250,"depth":250,"height":250},
  {"id":"anycubic-vyper","vendor":"Anycubic","model":"Vyper","width":250,"depth":255,"height":265},
  {"id":"qidi-q1-pro","vendor":"Qidi","model":"Q1 Pro","width":245,"depth":245,"height":240},
  {"id":"qidi-x-plus-3","vendor":"Qidi","model":"X-Plus 3","width":280,"depth":280,"height":270},
  {"id":"qidi-x-plus-4","vendor":"Qidi","model":"X-Plus 4","width":305,"depth":305,"height":280},
  {"id":"qidi-x-max-3","vendor":"Qidi","model":"X-Max 3","width":325,"depth":325,"height":315},
  {"id":"sovol-sv06","vendor":"Sovol","model":"SV06","width":220,"depth":220,"height":250},
  {"id":"sovol-sv06-plus","vendor":"Sovol","model":"SV06 Plus","width":300,"depth":300,"height":340},
  {"id":"sovol-sv07","vendor":"Sovol","model":"SV07","width":220,"depth":220,"height":250},
  {"id":"sovol-sv08","vendor":"Sovol","model":"SV08","width":350,"depth":350,"height":345},
  {"id":"flashforge-adventurer-5m","vendor":"Flashforge","model":"Adventurer 5M","width":220,"depth":220,"height":220},
  {"id":"flashforge-adventurer-5m-pro","vendor":"Flashforge","model":"Adventurer 5M Pro","width":220,"depth":220,"height":220},
  {"id":"flashforge-ad5x","vendor":"Flashforge","model":"AD5X","width":220,"depth":220,"height":220},
  {"id":"artillery-sidewinder-x2","vendor":"Artillery","model":"Sidewinder X2","width":300,"depth":300,"height":400},
  {"id":"artillery-genius-pro","vendor":"Artillery","model":"Genius Pro","width":220,"depth":220,"height":250},
  {"id":"anker-m5","vendor":"Anker","model":"M5","width":235,"depth":235,"height":250},
  {"id":"voron-2-4-300","vendor":"Voron","model":"2.4 300","width":300,"depth":300,"height":275},
  {"id":"voron-trident-300","vendor":"Voron","model":"Trident 300","width":300,"depth":300,"height":250},
];
